### ISSUE TITLE
[Bug Report] Server Crashing on Mod Loading 

### ISSUE THREAD

**Issue by Rage-GitHub** [jpenilla/MiniMOTD#102]
**Describe the bug**
Server crashes upon loading 2.0.5 or 2.0.7 version of mod.

**To Reproduce**
1. Install either version to your servers mod folder
2. Launch server and inspect that it crashes

**Expected behavior**
Server should run with the mod and not crash.

**Server Software and Version:**
 - Vendor: Fabric
 - Minecraft Version: 1.18.1

**Additional**
[latest.log](https://github.com/jpenilla/MiniMOTD/files/8759474/latest.log)

**Comment by jpenilla** [comment]
2.0.7 is for 1.18.2. It is not expected to work on 1.18.1. 2.0.5 works on 1.18.1, I see you claim to have an issue with that version, but didn't provide a log. However even with a log, only the latest version of MiniMOTD is supported.

**Comment by Rage-GitHub** [comment]
That's really unfortunate, I tried 2.0.5 but it does indeed crash. I'll provide a log.

**Comment by jpenilla** [comment]
You need to either downgrade loader to 0.13.x for that version, or manually install the newest adventure-platform-fabric mod
