### ISSUE TITLE
[Bug Report] When the Fake Player function is enabled, the server crashes when the player enters.

### ISSUE THREAD

**Issue by KoTeHok22** [jpenilla/MiniMOTD#108]
When the player enters, there is a conflict between the fakeplayerapi library and the create mod. Is it possible to fix it somehow?
[crash-2022-07-12_15.49.34-server.txt](https://github.com/jpenilla/MiniMOTD/files/9094970/crash-2022-07-12_15.49.34-server.txt)

Fabric Server

**Comment by jpenilla** [comment]
duplicate https://github.com/jpenilla/MiniMOTD/issues/104
