### ISSUE TITLE
[Bug Report] Server crashes upon loading chunks with certain Create blocks

### ISSUE THREAD

**Issue by Miv2nir** [jpenilla/MiniMOTD#110]
**Describe the bug**
Upon placing down the Deployer block from Create for fabric, the server crashes. It then keeps crashing if anyone happens to load the chunks with this block.

**To Reproduce**
1. Install Create and MiniMOTD on a 1.18.2 Fabric server
2. Log in and place down the Deployer block
3. Witness the crash

**Expected behavior**
The server should not crash.

**Server Software and Version:**
 - Vendor: Fabric
 - Minecraft Version: 1.18.2
 - Fabric version info: Loader version 0.14.8; Launcher version 0.11.0 (See Fabric server core version namings)

**Additional context**
[crashe_reporte.txt](https://github.com/jpenilla/MiniMOTD/files/9116674/crashe_reporte.txt)

**Comment by jpenilla** [comment]
Duplicate #104
