### ISSUE TITLE
[Feature Request] MiniMOTD API

### ISSUE THREAD

**Issue by kaxon-dev** [jpenilla/MiniMOTD#111]
**Is your feature request related to a problem? Please describe.**
I have server events that happen on a cycle and it would be great if my plugin could force a certain MOTD to show during specific times.

**Describe the solution you'd like**
A MiniMOTD API.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jpenilla** [comment]
duplicate #64
