### ISSUE TITLE
[Bug Report 1.18.2] Netty Error

### ISSUE THREAD

**Issue by itsdinkd** [jpenilla/MiniMOTD#113]
**Describe the bug**
This netty error is spamming my console over and over again. logs below.

**Expected behavior**
Not to spam

**Logs**
https://pastebin.com/8QadeLxQ

**Server Software and Version:**
 - Vendor: Fabric
 - Minecraft Version: 1.18.2

**Comment by jpenilla** [comment]
Please open a new issue if this is reproducible in 1.19.2, 1.18.2 will not be getting any new MiniMOTD builds
