### ISSUE TITLE
[Feature Request] Whole server playercount placeholder for player-count-settings

### ISSUE THREAD

**Issue by TomLewis** [jpenilla/MiniMOTD#134]
**Is your feature request related to a problem? Please describe.**
I cant seem to find a way to show the full playcount on the whole network in the player-count-settings, I have `virtual-host-configs` setup in proxy-settings in plugin_settings.yml for each server, which displays the specific number of players on that server, which is great, but for one of the servers (My main IP) I want it to display ALL the users connected to the network no matter what server they are on.

**Describe the solution you'd like**
A section in the player-count-settings to disaply all online players on the proxy total.

**Describe alternatives you've considered**
Placeholders to display in fake-players.

**Comment by TomLewis** [comment]
Bump!

**Comment by TomLewis** [comment]
Bump, I would really like to show all online players.

**Comment by jpenilla** [comment]
#171
