### ISSUE TITLE
Why can't I display my expression normally like this? Isn't it not supported? How should I follow the format of MiniMessgae? This is my configuration file

### ISSUE THREAD

**Issue by pipixixi233** [jpenilla/MiniMOTD#143]
# MiniMOTD Main Configuration

# Enable server list icon related features
icon-enabled=true
# Enable MOTD-related features
motd-enabled=true
# The list of MOTDs to display
# 
# - Supported placeholders: <online_players>, <max_players>
# - Putting more than one will cause one to be randomly chosen each refresh
motds=[
    {
        # Set the icon to use with this MOTD
        #  Either use 'random' to randomly choose an icon, or use the name
        #  of a file in the icons folder (excluding the '.png' extension)
        #    ex: icon="myIconFile"
        icon=random
        line1="<rainbow>\U+2764腐竹大大总是疏于管理 \U+2764"
        line2="希望大家多多支持 <gradient:blue:red>！希望大家多多支持 ！\u1F600"
    },
    {
        # Set the icon to use with this MOTD
        #  Either use 'random' to randomly choose an icon, or use the name
        #  of a file in the icons folder (excluding the '.png' extension)
        #    ex: icon="myIconFile"
        icon=random
        line1="<blue>\U+1F6E7 欢迎加入泡面的私人服务器 <bold><red>W0W \U+1F6E7"
        line2="<italic><underlined><gradient:red:green>欢迎加入 wow \U+1F6E7"
    }
]
player-count-settings {
    # Should the displayed online player count be allowed to exceed the displayed maximum player count?
    # If false, the online player count will be capped at the maximum player count
    allow-exceeding-maximum=false
    # Setting this to true will disable the hover text showing online player usernames
    disable-player-list-hover=true
    # Settings for the fake player count feature
    fake-players {
        # Modes: add, constant, minimum, random, percent
        # 
        # - add: This many fake players will be added
        #     ex: fake-players="3"
        # - constant: A constant value for the player count
        #     ex: fake-players="=42"
        # - minimum: The minimum bound of the player count
        #     ex: fake-players="7+"
        # - random: A random number of fake players in this range will be added
        #     ex: fake-players="3:6"
        # - percent: The player count will be inflated by this much, rounding up
        #     ex: fake-players="25%"
        fake-players="25%"
        # Enable fake player count feature
        fake-players-enabled=false
    }
    # Setting this to true will disable the player list hover (same as 'disable-player-list-hover'),
    # but will also cause the player count to appear as '???'
    hide-player-count=false
    # Changes the Max Players to be X more than the online players
    # ex: x=3 -> 16/19 players online.
    just-x-more-settings {
        # Enable this feature
        just-x-more-enabled=false
        x-value=3
    }
    # Changes the Max Players value
    max-players=69
    # Enable modification of the max player count
    max-players-enabled=true
}

**Comment by jpenilla** [comment]
This issue is not formatted properly and I'm not sure what specifically you are having trouble with. In general, MiniMOTD supports any characters supported by the base game, but you will need to ensure your editor is using UTF-8 encoding.
