### ISSUE TITLE
[Bug Report] plugin writes to config file

### ISSUE THREAD

**Issue by Jannik44** [jpenilla/MiniMOTD#168]
**Describe the bug**
The plugin seems to write to the config file during the reload/start process, but it looks like nothing changed, despite that my os informs me that the file has changed, you should probably open the file in readonly mode

**Screenshots**
![grafik](https://github.com/jpenilla/MiniMOTD/assets/76906033/46a1ebe9-179a-434f-b62c-c590873f453d)

**Server Software and Version:**
 - Vendor: Purpurmc
 - Minecraft Version: 1.20.4
 - Output of /version command: Current: git-Purpur-2120 (MC: 1.20.4)

**Additional context**

**Comment by jpenilla** [comment]
Not a bug, the writeback behavior is intentional and there are cases where transformations will be done.
