### ISSUE TITLE
[Bug Report] fakeplayers not working on purpurmc

### ISSUE THREAD

**Issue by Jannik44** [jpenilla/MiniMOTD#169]
**Describe the bug**
it looks like only the fakeplayer functionality isnt working, the player count is still the same, max player modification and motd is working fine

**To Reproduce**
use the default config file with changes to the fp options:

`# MiniMOTD Main Configuration

# Enable server list icon related features
icon-enabled=true
# Enable MOTD-related features
motd-enabled=true
# The list of MOTDs to display
# 
# - Supported placeholders: <online_players>, <max_players>
# - Putting more than one will cause one to be randomly chosen each refresh
motds=[
    {
        # Set the icon to use with this MOTD
        #  Either use 'random' to randomly choose an icon, or use the name
        #  of a file in the icons folder (excluding the '.png' extension)
        #    ex: icon="myIconFile"
        icon=random
        line1="<rainbow>MiniMOTD Default"
        line2="MiniMessage <gradient:blue:red>Gradients"
    },
    {
        # Set the icon to use with this MOTD
        #  Either use 'random' to randomly choose an icon, or use the name
        #  of a file in the icons folder (excluding the '.png' extension)
        #    ex: icon="myIconFile"
        icon=random
        line1="<blue>Another <bold><red>MOTD"
        line2="<italic><underlined><gradient:red:green>much wow"
    }
]
player-count-settings {
    # Should the displayed online player count be allowed to exceed the displayed maximum player count?
    # If false, the online player count will be capped at the maximum player count
    allow-exceeding-maximum=false
    # Setting this to true will disable the hover text showing online player usernames
    disable-player-list-hover=true
    # Settings for the fake player count feature
    fake-players {
        # Modes: add, constant, minimum, random, percent
        # 
        # - add: This many fake players will be added
        #     ex: fake-players="3"
        # - constant: A constant value for the player count
        #     ex: fake-players="=42"
        # - minimum: The minimum bound of the player count
        #     ex: fake-players="7+"
        # - random: A random number of fake players in this range will be added
        #     ex: fake-players="3:6"
        # - percent: The player count will be inflated by this much, rounding up
        #     ex: fake-players="25%"
        fake-players="3:6"
        # Enable fake player count feature
        fake-players-enabled=true
    }
    # Setting this to true will disable the player list hover (same as 'disable-player-list-hover'),
    # but will also cause the player count to appear as '???'
    hide-player-count=false
    # Changes the Max Players to be X more than the online players
    # ex: x=3 -> 16/19 players online.
    just-x-more-settings {
        # Enable this feature
        just-x-more-enabled=false
        x-value=3
    }
    # Changes the Max Players value
    max-players=250
    # Enable modification of the max player count
    max-players-enabled=true
}`
**Screenshots**
![grafik](https://github.com/jpenilla/MiniMOTD/assets/76906033/36f6859b-b95d-4d0f-8ece-15339a22285a)

**Server Software and Version:**
 - Vendor: purpurmc
 - Minecraft Version: 1.20.4
 - Output of /version command: Current: git-Purpur-2120 (MC: 1.20.4)

**Comment by jpenilla** [comment]
Unable to reproduce on Paper 1.20.4, between 3 and 6 are added to the player count randomly as expected.

**Comment by Jannik44** [comment]
> Unable to reproduce on Paper 1.20.4, between 3 and 6 are added to the player count randomly as expected.

i tried also with fake-players="30:60" but nothing shows up, is maybe the syntax wrong, do i have to add -random in front of the line or smth, or tabs and spaces mixed?

**Comment by jpenilla** [comment]
```diff
-        fake-players="25%"
+        fake-players="3:6"
         # Enable fake player count feature
-        fake-players-enabled=false
+        fake-players-enabled=true
```
This is the only change I made to the default config.

**Comment by Jannik44** [comment]
okay, i found the issue, luckily its not a bug in your plugin its an issue with a functionality with SuperVanish because both plugins collide with each other at the player numbers, will inform the other developer, thanks for your help!
