### ISSUE TITLE
[Feature Request] perDomainStatus

### ISSUE THREAD

**Issue by F3F5** [jpenilla/MiniMOTD#185]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

      example:
        domain: example.com
        description:
          activated: true
          text:
            - "&3Use IP example.com to connect to the server!"
        favicon:
          activated: false
          file: example.png

**Describe alternatives you've considered**
https://github.com/AlexProgrammerDE/PistonMOTD

**Additional context**

**Comment by jpenilla** [comment]
https://github.com/jpenilla/MiniMOTD/wiki#advanced-configuration

**Comment by F3F5** [comment]
> https://github.com/jpenilla/MiniMOTD/wiki#advanced-configuration

PistonMod also work for Spigot

**Comment by F3F5** [comment]
And how to config perdomain?
