### ISSUE TITLE
[Feature Request] Player count does not include specific players

### ISSUE THREAD

**Issue by huguyt** [jpenilla/MiniMOTD#194]
**Request**
Can you add a feature so that the player count doesn't count specific players?
I am a server administrator, but some players always use the player count to detect whether the OP is online.
There will be hackers testing the client in the middle of the night while the server is empty.
By the way, I am using the velocity version of the plugin.

**Solution**
Add a blacklist file and don't count the players in it.

**Describe alternatives you've considered**
Add a permission to prevent specific players from being counted.

**Additional context**
There may be grammatical issues because I used Google Translate. Sorry about that.

**Comment by jpenilla** [comment]
This is typically handled by a vanish plugin or a general admin tools plugin. MiniMOTD will respect the updated player counts set by those other plugins. No plans to include this in MiniMOTD.
