### ISSUE TITLE
[Bug Report] In version 1.21, the option "disable-player-list-hover=true" does not work on the server

### ISSUE THREAD

**Issue by Xbaishu** [jpenilla/MiniMOTD#211]
After enabling the minimotd plugin on my server, I discovered that the option “disable-player-list-hover=true” does not function as intended on the server. Player IDs are still displayed in the server list. Currently, the only tested option that works is “hide-player-count=true”, but it also results in the appearance of question marks (as noted in the comments).
![QQ_1720850819736](https://github.com/user-attachments/assets/598894eb-96e7-4488-b2bc-45a659b139ea)

The setting “disable-player-list-hover=true” did not take effect and did not cause any errors on the server.
Java: jdk-21
Server Version: 1.21 
Server Core: Paper-1.21-38 Paper version: 1.21-38-master@1f5db50 (2024-06-27T20:15:58Z) (Implementing API version 1.21-R0.1-SNAPSHOT) 
minimotd plugin version: 2.1.2

Other plugins: 
GroupManager 
SuperVanish 
EssentialsX 
ViaVersion 
ProtocolLib (dev#723)

**Comment by CaesarGalahad** [comment]
I'm also having this issue Pls is it fixed now

**Comment by Baktus79** [comment]
Same here

**Comment by jpenilla** [comment]
The Paper bug is fixed in 1.21.1 build 76
