### ISSUE TITLE
[Feature Request] Ingame command to edit motd 

### ISSUE THREAD

**Issue by LutrexMC** [jpenilla/MiniMOTD#237]
**Is your feature request related to a problem? Please describe.**
Unfortunately, you cannot change the MOTD quickly, e.g. for spontaneous maintenance. That's why I think the idea makes sense.

**Describe the solution you'd like**
The idea would be a command e.g. `/minimotd edit <line> <text>`
to edit the MOTD in the game.

**Describe alternatives you've considered**
You always have to open the file, edit it, save it and reload the plugin. That takes a lot of time.

**Additional context**
-

**Comment by jpenilla** [comment]
This isn't something I'm interested in adding. In my opinion, it would just be not very useful bloat. You would need to leave the game again to see the server list and check your changes anyway.
