### ISSUE TITLE
[Feature Request] Different MOTDs for hostnames (velocity)

### ISSUE THREAD

**Issue by LeoDog896** [jpenilla/MiniMOTD#36]
**Is your feature request related to a problem? Please describe.**
I can't display different MOTDs for different hostnames -- in my scenario I have a build and a gameplay server that I want to differerntriate.

**Describe the solution you'd like**
Mabye some sort of subcategory using the hostname as a paramater?

**Comment by jackmawer** [comment]
Just bumping this suggestion.
In the meantime, a workaround is to put MiniMOTD on each server and use velocity's full motd passthrough option. I personally like having it controlled from the proxy though.

**Comment by jpenilla** [comment]
implemented in - https://github.com/jpenilla/MiniMOTD/commit/50158a1a81aeb9a6fa722f02d9347ddb4e718a66

snapshot download: https://jenkins.jpenilla.xyz/job/MiniMOTD/lastSuccessfulBuild/
