### ISSUE TITLE
[Feature Request] Cache players to improve performance

### ISSUE THREAD

**Issue by kaxon-dev** [jpenilla/MiniMOTD#38]
**Is your feature request related to a problem? Please describe.**

I have a velocity server with over 1000 players at peak times, and it would be useful if players are cached whenever they ping the server.

**Describe the solution you'd like**

A feature such as CleanMotD's to cache players; I'd use them but they don't support velocity:
[https://github.com/2LStudios-MC/CleanMotD/blob/master/src/dev/_2lstudios/cleanmotd/bungee/listeners/ProxyPingListener.java](https://github.com/2LStudios-MC/CleanMotD/blob/master/src/dev/_2lstudios/cleanmotd/bungee/listeners/ProxyPingListener.java)

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by jmanpenilla** [comment]
It doesn't really look like they are "caching" anything, they are simply not sending the favicon to players who have already been sent it. I could add similar functionality to MiniMOTD but I have doubts that it will actually make any sort of performance difference

**Comment by jpenilla** [comment]
Closing due to lack of response
