### ISSUE TITLE
[Feature Request] Pastel Rainbow

### ISSUE THREAD

**Issue by mibby** [jpenilla/MiniMOTD#46]
Would it be possible to add a <PastelRainbow> color? Similar to rainbow but pastel colors only.

**Comment by jpenilla** [comment]
Yes it is a "possibility" but it is not something I would add to the plugin. This is a perfect use case for a gradient. Using a gradient you can select the colors you want and you can decide what "pastel colors" means to you, as the colors I choose might be different than what you want.

Here is an example I tested:
![](https://i.imgur.com/E0ZmusI.png)
`<gradient:#ff8b8b:#f5ffa2:#aaffa2:#9fd1ff:#ffaef7>|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||`
![](https://i.imgur.com/a5NyXum.png)
