### ISSUE TITLE
[Bug Report] MOTD formatting text is cleared on reload

### ISSUE THREAD

**Issue by seanchristians** [jpenilla/MiniMOTD#48]
**Describe the bug**
Formatting tags are removed after running `minimotd reload`

**To Reproduce**
1. Open `config/MiniMOTD/main.conf`
1. `icon-enabled: false`
1. `motd-enabled: true`
1. Create a single motd entry.
1. Write minimessage-style formatted text for motd lines 1 and 2
1. Save and close the config file.
1. Run `/minimotd reload` on the server
1. Re-open the config file.

**Expected behavior**
I expect my formatting to persist across reloads.

**Server Software and Version:**
 - Vendor: Fabric
 - Minecraft Version: 1.16.5

**Additional context**
N/A

**Comment by jpenilla** [comment]
Are there any errors in the console? Could you share the `main.conf` file (via something like https://paste.gg/) that doesn't save properly?

**Comment by seanchristians** [comment]
Wow, thanks for the quick reply!

The console doesn't seem to throw any errors:
```
[MiniMOTD] Reloading MiniMOTD...[MiniMOTD] Done reloading MiniMOTD
```
Here's my main.conf:
https://paste.gg/p/anonymous/28ea85b60c0942cc9aff6f21ceeb4455

**Comment by jpenilla** [comment]
Hmm, to be honest I have no idea what could cause the config to become modified like that... I tested adding the motd you provided to my config, and also tried with it as the only motd in the config
```ini
    {
        icon="random"
        line1="<white><b>Foo</white>   \u23d0   </b><red><underlined>Bar</underlined></red>"
        line2="<light_purple>Baz</light_purple>"
    }
```
and for me, it loaded and saved properly, resulting in this motd
![image](https://user-images.githubusercontent.com/11360596/110867755-24ce7d80-827c-11eb-8c15-273c4431052a.png)

For me to fix this I need to be able to reproduce it or understand what's causing it, but I don't remove formatting from text in this way anywhere in the mod, so I'm pretty confused.
Could you provide a list of other mods you are using, as well as information about your java install and OS? Theres a chance replicating your setup could help me reproduce this issue.

**Comment by seanchristians** [comment]
Sorry to have wasted your time, I was using a cloud-based server hosting interface (due to them having a lack of ssh access). It seems the website was trying to parse the formatting tags as HTML tags and just removed them every time I opened the file with their interface.
