### ISSUE TITLE
[Feature Request] Unicode characters support

### ISSUE THREAD

**Issue by Jakubk15** [jpenilla/MiniMOTD#65]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't use Unicode characters in MiniMOTD.

**Describe the solution you'd like**
I want to add Unicode characters support to MiniMOTD, because when I put unicode character in MOTD, it doesn't appear.

**Describe alternatives you've considered**
The only alternative here is using different MOTD plugin.

**Comment by jpenilla** [comment]
Ensure you are preserving the UTF-8 encoding of the config files. Beyond that, how the client renders characters is out of my control.

**Comment by bloodyeyesblackblood** [comment]
> MiniMOTD is compatible with Unicode characters. Ensure you are preserving the UTF-8 encoding of the config files. Beyond that, how the client renders characters is out of my control.

hej, i don't find anything in the wiki neither kyori docs to unicode and/or utf-8 encodings? could you u please explain to me what i need to do?
