### ISSUE TITLE
[Bug Report] This happens when another thing should have

### ISSUE THREAD

**Issue by lerokko** [jpenilla/MiniMOTD#66]
**Describe the bug**
A clear and concise description of what the bug is. I have 2 Servers that are the same 1 for testing and 1 for production. The testserver is on java 8 while the production one is on java 11. Somewhere between paper build 562 and 648 it breaks in java 11 but not in java 8 (/minimotd commands are still executable but the server motd from server.properties is loaded.)

I tested like a dozen builds from 648 to latest today. I should have done a binary search maybe but its late and this problem is only happening in my production environment so I cannot test it on my testserver.

**Server Software and Version:**
 - Vendor: Paper
 - Minecraft Version: 1.16.5
 - git-Paper-562 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 172 version(s) behind

**Comment by lerokko** [comment]
Oh wow I really tired. Can I edit the title?

**Comment by lerokko** [comment]
I cant...

**Comment by jpenilla** [comment]
I've tested Java 8, 11, and 16 with Paper 1.16.5 build 748, and have been unable to reproduce any issues.

**Comment by lerokko** [comment]
When going from Paper build 587 to 588 I get hits warning in the console:

[13:13:08] [Server thread/WARN]: Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.

I do not know if its related to Minimotd but it was not there in 587. BUt it only apprears in the builds where minimotd is not working correctly.
I get the warning both on openjdk version "1.8.0_282" and openjdk 11.0.8 2020-07-14 but on the latter the motds are not loading

Paper fixed these to bugs in that build. https://github.com/PaperMC/Paper/issues/5473 and https://github.com/PaperMC/Paper/pull/5474

**Comment by jpenilla** [comment]
MiniMOTD has nothing to do with MySQL. If you are able to provide reproduction steps please open a new issue.
