### ISSUE TITLE
[Feature Request] The MOTD Change on older versions of minecraft!

### ISSUE THREAD

**Issue by athkiasaris1** [jpenilla/MiniMOTD#67]
I like the gradients but I don't like how on old versions it looks like that.

So the solution I thought is the motd will change on old versions of minecraft set in the config (on 1.16 motd gradients but 1.15- something else)

An alternative solution will be to check if the version of minecraft is compatible with gradients, if not the plugin will show the normal bungeecord motd.
 
Note: **I don't know if this is possible.**

**Comment by jpenilla** [comment]
MiniMOTD already downsamples colors where the server gives us enough information to know we need to do so.

Closing as this is a duplicate of #19
