### ISSUE TITLE
[Feature Request] Maintenance mode and Wrong Protocol Version

### ISSUE THREAD

**Issue by OverBrave** [jpenilla/MiniMOTD#73]
Can you bring a maintenance mode?
Also, if the player is not in the required version, can you provide a special MOTD display for him?

 What will it include:
Custom MOTD, Custom ICON, Closing logins to server and sending maintenance message when try to join server.

**Comment by jpenilla** [comment]
One issue per feature request please. This is also somewhat a duplicate of #19
