### ISSUE TITLE
[Bug Report] 1.18 Support

### ISSUE THREAD

**Issue by weihao** [jpenilla/MiniMOTD#82]
On 1.18, it does not show RGB.

**Comment by jpenilla** [comment]
I can't reproduce this, additionally there is little to no information to go off of here as far as troubleshooting. Please open a new issue with details about your environment, reproduction steps, etc, or better yet just ask for help in discord instead.

**Comment by weihao** [comment]
Where can I find discord link?

**Comment by jpenilla** [comment]
https://discord.gg/86Ekw8H
