### ISSUE TITLE
[Feature Request] MiniMOTD for forge servers

### ISSUE THREAD

**Issue by kakigorimochi** [jpenilla/MiniMOTD#85]
I currently run a server for a group of friends running forge and look if I can tweak our server's MOTD with gradient effects.
I happen to run into this plugin via google and found it doesn't have forge support. It would be great for this to be available to forge servers too.

If it is not possible, is there a reason why?

**Comment by ahnaf-zamil** [comment]
I second this, I run a Forge server as well and I need this plugin ._.

**Comment by PavelGuet** [comment]
try using Mohist or Arclight

**Comment by Chun-QiuCC** [comment]
I think you need this: https://github.com/TomatoPuddin/MiniMOTD-forge
