### ISSUE TITLE
[Bug Report] Configuration Error?

### ISSUE THREAD

**Issue by A2577467404** [jpenilla/MiniMOTD#86]
**Describe the bug**

**To Reproduce**
1. Dig straight down
2. Right click 5 times
3. Craft a Netherite Hoe

**Expected behavior**

**Screenshots**

**Server Software and Version:**
 - Vendor: Bungeecord
 - Minecraft Version: 1.8.8
 - Output of /version command: Command Not Found?

**Additional context**
Configuration items for just-X-more and Max-players have been reversed

**Comment by jpenilla** [comment]
Improperly filled out issue template
