### ISSUE TITLE
[Feature Request] Take over Bungee messages.properties to reload live!

### ISSUE THREAD

**Issue by TomLewis** [jpenilla/MiniMOTD#88]
**Is your feature request related to a problem? Please describe.**
Theres no easy way to quickly edit the bungee [messages.properties](https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/resources/messages.properties) file and reload it without rebooting the bungee server while everything is running, specifically when the server fills up I wish to be able to change the server full message.
Would be nice to also change the restating message live too depending on changes/maintenence periods.
Same for the server_went_down.

It would just be nice to be able to reload this file live.

**Describe the solution you'd like**
A file in the same formats you use to easily use color/gradients and to reload these messages live without rebootin the server.

**Describe alternatives you've considered**
Restarting the bungee every time.

**Comment by jpenilla** [comment]
I don't think I fully understand what you're asking for, but from what I do understand it seems completely out of scope for MiniMOTD

**Comment by jpenilla** [comment]
closing due to lack of response

**Comment by TomLewis** [comment]
Live reloading of bungee messages.
