### ISSUE TITLE
[Bug Report] Fake players is invalid

### ISSUE THREAD

**Issue by AdminHcat** [jpenilla/MiniMOTD#89]
**Describe the bug**

**To Reproduce**
Fake players is invalid

**Screenshots**
![image](https://user-images.githubusercontent.com/50044729/151700596-db047d23-0988-4bc1-82ee-c3fe7b14af4e.png)
![image](https://user-images.githubusercontent.com/50044729/151700628-b743d081-5cb0-49bd-a9fd-588f27128835.png)

**Server Software and Version:**
 - Vendor: Purpur、paper
 - Minecraft Version: 1.18.1

**Additional context**

**Comment by jpenilla** [comment]
Issue template not properly filled out

**Comment by AdminHcat** [comment]
Incompatible with superVanish plugin
