### ISSUE TITLE
[Feature Request] Customise hover over for player count

### ISSUE THREAD

**Issue by TomLewis** [jpenilla/MiniMOTD#92]
**Is your feature request related to a problem? Please describe.**
Once #91 is fixed.

Allow us to customize what is shown when hovering over player counts

**Describe the solution you'd like**
Allow us to specify exactly what we want when hovering over player counts and placeholders like %random_player% %online@server% %online@world%.

For example in ServerListPlus I was able to use ` &a%random_players@survival,3|, %` which showed 3 random players online to that specific server.

Here is what I used to use:
```
  Players:
    Hover:
    - |-
      &eAhoy scallywag, get ye booty on PirateCrarft!
      
        - &aSurvival: &e%online@survival%/100 players online
        - &aCreative: &e%online@creative%/50 players online
        - &aTest: &e%online@test%/50 players online

      &a%random_players@survival,3|, %

      &aJoin now and play together with %random_player% ...
```

**Describe alternatives you've considered**
ServerListPlus

**Comment by jpenilla** [comment]
duplicate https://github.com/jpenilla/MiniMOTD/issues/70

**Comment by TomLewis** [comment]
Wanted feature then.
