### ISSUE TITLE
[Bug Report] Fabric Server Crash Minecraft 1.18.2

### ISSUE THREAD

**Issue by Yavoroshko** [jpenilla/MiniMOTD#99]
**Describe the bug**
Server crash

**To Reproduce**
1. Start server

**Expected behavior**
I want server to start and plugin to work)

**Screenshots**

**Server Software and Version:**
 - Vendor: Fabric
 - Minecraft Version: 1.18.2
 - Output of /version command: fabric don`t have this command

**Additional context**
Fabric API v0.47.10
[latest.log](https://github.com/jpenilla/MiniMOTD/files/8228460/latest.log)

**Comment by iSkeptical** [comment]
Having same issue as listed.

**Comment by jpenilla** [comment]
You'll need to use the snapshot builds for 1.18.2 until a new release is made https://jenkins.jpenilla.xyz/job/MiniMOTD/
